name: agile_card_selector
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  #state
  flutter_bloc: ^8.1.1
  equatable:

  #ui/ux
  flutter_svg: ^1.1.6
  font_awesome_flutter: ^10.3.0
  stacked_card_carousel: ^0.0.4
  flip_card: ^0.6.0

  #general
  flutter_launcher_icons: ^0.11.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/

